### ISSUE TITLE
Create user functionality

### ISSUE THREAD

**Issue by BillyLuisNeedham** [BillyLuisNeedham/yilly-app#1]
## Todo
- [x] Domain
- [x] Data - in memory data source for users
- [x] Presentation
- [ ] Data - in memory data source for users refactored to use postgreSQL
- [ ] Additional thoughts have been considered and actioned if required

**Comment by BillyLuisNeedham** [comment]
## Domain
### Todo
- [x] Build out user model
- [x] Build out a userRequest model
- [x] Get jest to work with type script
- [x] Build out a createUserUserCase TDD
- [x] Move domain out of src and into its own domain dir at root level
- [x] Refactor CreateUserUseCase to return a result instead of a user

**Comment by BillyLuisNeedham** [comment]
## Data 
### Concept
- Takes the use cases from the domain layer and handles injecting the repositories in.
- Responsible for providing implementations of the repositories.
- Handles exporting the use cases that have had dependency injection to the presentation layer.
    - Presentation layer is only aware of data layer.
        - This could potentially be managed by the index.ts at the root of the layer exporting the one layer above it.

### TODO 
- [x] Build out data layer 
- [x] Build out UserRepository which initially just stores a user in memory
- [x] See it work
- [x] Hook into Presentation layer
- [x] Remove Result file
- [x] Refactor Unit tests
- [ ] When working from presentation layer to data layer, replace UserRepository in memory with PostgresSQL

**Comment by BillyLuisNeedham** [comment]
## Presentation
### Concept
- Takes a POST to /user with the body of a CreateUserRequest
- Returns the created user body
- Should also validate whether the body is a CreateUserRequest and return a 400 if not

### TODO 
- [x] Build out post /user 
- [x] Build out error flow from post /user
- [x] Hook post /user into data layer
    - [x] See it log in UserDataSourceInMemory
    - [x] Convert UserRouter.js into a typescript file
    - [ ] Requests without name and or email are getting through validation in UserRouter

**Comment by BillyLuisNeedham** [comment]
## Additional thoughts 
- [x] It may be worth changing CreateUserUseCase to return some sort of a result component as opposed to a User class
- [ ] Is it worth having a useCase for name and another for email validation that is used as part of the domain layer. 
    - they could return individual errors that are checked for in the presentation layer and that could dictate which result is sent back via express
- [ ] Should I add unit tests confirming that errors from classes also come through?
    - [ ] Look [here](https://javascript.info/custom-errors) for custom error class if needed
